version: '3'
services:
 db:
   image: mysql:8.0-ubuntu20.04
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: toor
   ports:
     - 3306:3306
   volumes:
     - ./:/mysql

 backend:
    image: ubuntu:20.04
    # command: apt-get update && apt-get install -yq python3 python3-pip
    # command: DEBIAN_FRONTEND=noninteractive apt install -yq python3-dev default-libmysqlclient-dev build-essential mysql-client
    # command: python3 -m pip install mysql 
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    # environment:
     # MYSQL_ROOT_PASSWORD: toor
    ports:
     - 5000:5000
    volumes:
     - ./:/v3
